<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?php echo $data['title'];?> | ACWPD Random Password Generator</title>
        <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:600|PT+Mono|Source+Sans+Pro" rel="stylesheet">
		<link href="/css/bootstrap.min.css" rel="stylesheet">
		<link href="/css/custom.css" rel="stylesheet">
		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

			ga('create', 'UA-48537533-4', 'auto');
			ga('send', 'pageview');
		</script>
	</head>
    <body>
        <div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="page-header">
						<h1 id="header" class="text-center">ACWPD Random Password Generator</h1>
						<h2>Article: <?php echo $data['title'];?></h2>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<?php echo $data['body']; ?>
				</div>
			</div>
		</div>
	</body>
</html>
				